from .userCreateView import UserCreateView
from .pacienteCreateView import CrearPacienteView
from .psaludCreateView import CrearPersonalsaludView
from .familiarCreateView import FamiliarCreateView
from .consulpaciente import ConsulPaciente